export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const DECREASE_PRODUCT = "DECREASE_PRODUCT";
export const INCREASE_PRODUCT = "INCREASE_PRODUCT";
export const REMOVE_ALL = "REMOVE_ALL";
export const ADD_ALL = "ADD_ALL";